# Generated by Django 5.2.15 on 2026-06-21 00:56

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم الفئة')),
                ('kind', models.CharField(choices=[('income', 'مدخول'), ('expense', 'مصروف')], max_length=10, verbose_name='النوع')),
            ],
            options={
                'verbose_name': 'فئة مالية',
                'verbose_name_plural': 'الفئات المالية',
                'ordering': ['kind', 'name'],
                'unique_together': {('name', 'kind')},
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('income', 'مدخول'), ('expense', 'مصروف')], max_length=10, verbose_name='النوع')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='المبلغ')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='التاريخ')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='الوصف')),
                ('payment_method', models.CharField(choices=[('cash', 'نقداً'), ('check', 'شيك'), ('transfer', 'تحويل بنكي')], default='cash', max_length=10, verbose_name='طريقة الدفع')),
                ('receipt', models.FileField(blank=True, null=True, upload_to='finance/receipts/', verbose_name='الوصل/المرفق')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='finance.category', verbose_name='الفئة')),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='members.member', verbose_name='العضو المرتبط')),
            ],
            options={
                'verbose_name': 'عملية مالية',
                'verbose_name_plural': 'العمليات المالية',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
