# Generated by Django 5.2.15 on 2026-06-21 00:13

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('membership_number', models.CharField(max_length=20, unique=True, verbose_name='رقم العضوية')),
                ('full_name', models.CharField(max_length=150, verbose_name='الاسم الكامل')),
                ('national_id', models.CharField(blank=True, max_length=20, verbose_name='رقم البطاقة الوطنية')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='الهاتف')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='البريد الإلكتروني')),
                ('address', models.TextField(blank=True, verbose_name='العنوان')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='members/photos/', verbose_name='الصورة')),
                ('member_type', models.CharField(choices=[('regular', 'عادي'), ('honorary', 'شرفي'), ('founder', 'مؤسس')], default='regular', max_length=20, verbose_name='نوع العضوية')),
                ('status', models.CharField(choices=[('active', 'نشط'), ('suspended', 'موقوف'), ('withdrawn', 'منسحب')], default='active', max_length=20, verbose_name='الحالة')),
                ('join_date', models.DateField(default=django.utils.timezone.now, verbose_name='تاريخ الانخراط')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
            ],
            options={
                'verbose_name': 'عضو',
                'verbose_name_plural': 'الأعضاء',
                'ordering': ['membership_number'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(verbose_name='السنة')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='المبلغ')),
                ('payment_status', models.CharField(choices=[('paid', 'مدفوع'), ('unpaid', 'غير مدفوع')], default='unpaid', max_length=20, verbose_name='حالة الدفع')),
                ('payment_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الدفع')),
                ('notes', models.CharField(blank=True, max_length=255, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='members.member', verbose_name='العضو')),
            ],
            options={
                'verbose_name': 'اشتراك',
                'verbose_name_plural': 'الاشتراكات',
                'ordering': ['-year', 'member'],
                'unique_together': {('member', 'year')},
            },
        ),
    ]
